version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: telegram_bot
    depends_on:
      - api
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    command: poetry run python bot/bot.py
